version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  postgres:
    driver: local
  cache:
    driver: local
