# fly.toml app configuration file generated for sojourner-bo on 2023-08-13T16:02:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sojourner-bo"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  app = "bin/rails server"
  worker = "bundle exec good_job start --enable-cron --max-threads=2 --poll-interval=60"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[worker_service]
  processes = ["worker"]
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
