production:
  schedule:
    class: ScheduleJob
    schedule: every 2 minutes

  update_last:
    class: UpdateLastJob
    schedule: every day at 6

#  update_all:
#    class: UpdateAllJob
#    schedule: every month
