production:
  schedule:
    class: ScheduleJob
    schedule: every 3 hours

  update_last:
    class: UpdateLastJob
    schedule: '30 6-23 * * *'

#  update_all:
#    class: UpdateAllJob
#    schedule: every month
