production:
  schedule:
    class: ScheduleJob
    schedule: every 3 hours

  update_last:
    class: UpdateLastJob
    schedule: every day at 6:15

#  update_all:
#    class: UpdateAllJob
#    schedule: every month
